# Experiment parameters

results_path: '/home/gerda/Desktop/results'
exp_name: 'ssl test'

data_split: cifar10_default

num_classes: 10

# transform parameters
transform:
    name: transform_random_noise
    params:
        sigma: 0.01

# network architecture
arch:
    # name: simple_model
    # params: {}
    name: 'model_conv_small'
    params:
        activation: 'LeakyReLU'
        dropout: 0.5

optimizer:
    name: Adam
    params:
        learning_rate: 0.001

# loss function
loss: kl_divergence
alpha: 0

# training
batch_size: 128
epochs: 120
# epochs: 120 # should be enough to converge